# Generated by Django 3.1.5 on 2021-02-10 11:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-avatar-icon.png', null=True, upload_to=authentication.models.user_directory_path),
        ),
    ]
