# Generated by Django 3.1.5 on 2021-03-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='min_income',
        ),
    ]
