# Generated by Django 3.1.5 on 2021-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210404_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(max_length=1500),
        ),
        migrations.RemoveField(
            model_name='user',
            name='service_type',
        ),
        migrations.AddField(
            model_name='user',
            name='service_type',
            field=models.ManyToManyField(to='authentication.ServiceType'),
        ),
    ]
