# Generated by Django 3.1.5 on 2021-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_min_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='min_incomer',
            field=models.BooleanField(default=False),
        ),
    ]
