# Generated by Django 3.1.5 on 2021-01-27 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateTimeField()),
                ('ticket_received', models.BooleanField(default=False)),
                ('connector', models.CharField(blank=True, max_length=50, null=True)),
                ('pro', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.IntegerField(default=0)),
                ('date_sent_client', models.DateTimeField()),
                ('date_sent_pro', models.DateTimeField()),
                ('feedback_client', models.TextField(blank=True, null=True)),
                ('feedback_pro', models.TextField(blank=True, null=True)),
                ('comments_connector', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
