# Generated by Django 3.1.5 on 2021-03-25 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=1500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('about_me', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.IntegerField(choices=[(0, 'Amsterdam'), (1, 'Rodertam'), (2, 'not specified')], default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_received', models.BooleanField(default=False)),
                ('connector', models.PositiveIntegerField(blank=True, null=True)),
                ('pro', models.PositiveIntegerField(blank=True, null=True)),
                ('service_type', models.IntegerField(choices=[(0, 'kapper'), (1, 'schoonheidsspecialiste'), (2, 'pedicure'), (3, 'visagist'), (4, 'styliste'), (5, 'nagelstyliste'), (6, 'haarwerken'), (7, 'not specified')], default=7)),
                ('distance', models.IntegerField(default=0)),
                ('terms_approved', models.BooleanField(default=False)),
                ('is_pro_confirm', models.BooleanField(default=False)),
                ('is_client_confirm', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedBackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedbacks_images')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_images', to='ticket.feedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ticket.ticket'),
        ),
    ]
