# Generated by Django 3.1.5 on 2021-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('created_at', 'is_intake_call', 'updated_at')},
        ),
        migrations.AddField(
            model_name='ticket',
            name='intake_call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_intake_call',
            field=models.BooleanField(default=False),
        ),
    ]
