# Generated by Django 3.1.5 on 2021-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='appointment_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
