# Generated by Django 3.1.5 on 2021-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210129_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_sent_client',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_sent_pro',
            field=models.DateTimeField(blank=True),
        ),
    ]
