# Generated by Django 3.1.5 on 2021-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20210129_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_sent_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_sent_pro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
