# Generated by Django 3.1.5 on 2021-02-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20210214_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='area',
            field=models.IntegerField(choices=[(0, 'Amsterdam'), (1, 'Rodertam'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_client_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_pro_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
